### ISSUE TITLE
Save and quit from archipelago game makes main menu stop working

### ISSUE THREAD

**Issue by voidlily** [ArchipelagoMW-HollowKnight/Archipelago.APMapMod#16]
mod log attached

[ModLog.txt](https://github.com/ArchipelagoMW-HollowKnight/Archipelago.APMapMod/files/14826955/ModLog.txt)

**Comment by voidlily** [comment]
There's another issue that might also be in the same mod log, where map icons have a weird transparency now.

**Comment by BadMagic100** [comment]
Downgrade your mapchanger and rcpathfinder to the correct version, pinned in Archipelago discord

**Comment by BadMagic100** [comment]
Resolved in v2.2.0
