### ISSUE TITLE
Can't enable map mod

### ISSUE THREAD

**Issue by thislooksfun** [ArchipelagoMW-HollowKnight/Archipelago.APMapMod#3]
I installed this mod via Scarab+ and made sure all my other mods are up-to-date, but when I open an Archipelago save it doesn't give me the option to enable the mod. There's no button in the pause menu, and Ctrl+M does nothing. I checked the ModLog as well, but there isn't anything in there about anything obvious, but I'm attaching it anyway just in case: [ModLog.txt](https://github.com/ArchipelagoMW-HollowKnight/Archipelago.APMapMod/files/12472344/ModLog.txt)

**Comment by KonoTyran** [comment]
It looks like you are playing a save that was created with the old archipelago mod both the AP mod and APMapMod require a new save file when updating from old versions.

**Comment by thislooksfun** [comment]
Ah, that is unfortunate, especially for the map mod, but it kinda makes sense. Can I make a new save connecting to an existing AP game? Or would that break something?

**Comment by KonoTyran** [comment]
yes, if you make a new save both will work fine, you will get back all items you have sent out and received, so you only really lose current Geo (but get back all your relics and geo rock geo anyway so only lose out on enemy geo) and benches.
